ptm/Django_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include ,re_path
from django.conf import settings
from django.conf.urls.static import static
from mysite.admin import my_admin_site

urlpatterns = [
    path('admin/', my_admin_site.urls),
    url(r'', include('mysite.urls')),

 
]


if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ptm/mysite/urls.py
from django.conf.urls import url
from django.urls import path , include
from . import views
#REST API URLS


from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
 
    url(r'^$', views.home, name="home"),
    url(r'login/', views.login_user, name = 'login'),
    url(r'^logout/$', views.logout_user, name= "logout"),
    url(r'^register/$', views.register_user, name= "register"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    url(r'edit-profile/$', views.edit_profile, name="editProfile"),
    url(r'edit-profile-inform/$', views.edit_profile_user, name="editProfileUSer"),

    #Password Change URL............
    url(r'^change_password/$', views.change_password, name = "change_password"),

    #password Reset URLS...........
    path('password_reset/', PasswordResetView.as_view(), name='password_reset' ),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('contact/$', views.contact, name= "contact"),


    

    






  
  

  
]

ptm/mysite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import get_user_model

CHOICES_TYPE = (
    ('Buyer', 'Buyer'),
    ('Agent', 'Agent')
)

choice1 =(('Short Commute to work','Short Commute to work'),
          ('Access to shopping','Access to shopping'),
          ('Vastu Preference','Vastu Preference'),
          ('School Requirements','School Requirements'),
           )


class profileModel(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete= models.CASCADE)
    contactNumber = models.BigIntegerField(blank = True, null=True)
    approve = models.BooleanField(default=True)
    Teacher_or_Parent = models.CharField(max_length=10, blank=True, default='Buyer' ,choices=CHOICES_TYPE)
    occupation=models.CharField(max_length=200,blank=True,null=True)
    #Property Requirements
    Price_Range=models.CharField(max_length=200,blank=True,null=True)
    has_pre_approval=models.CharField(max_length=200,blank=True,null=True)
    property_type=models.CharField(max_length=200,blank=True,null=True)
    beds=models.CharField(max_length=200,blank=True,null=True)
    bath=models.CharField(max_length=200,blank=True,null=True)
    lot_size=models.CharField(max_length=200,blank=True,null=True)
    stories=models.CharField(max_length=200,blank=True,null=True)
    location_preference=models.CharField(max_length=200,blank=True,null=True)
    looking_to_buy_in_how_many_months=models.CharField(max_length=200,blank=True,null=True)
    How_long_have_you_been_house_hunting=models.CharField(max_length=200,blank=True,null=True)
    Life_style = models.CharField(max_length=200,blank=True,null=True,choices=choice1)
    any_other = models.CharField(max_length=200,blank=True,null=True)
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

ptm/mysite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import *
from django.contrib.auth import (authenticate, get_user_model, password_validation,)


#User Login Form ................
class loginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())



#User Registration Form...................
class registerForm(forms.ModelForm):
    password = forms.CharField(label = 'Password', widget = forms.PasswordInput(),strip=False,help_text=password_validation.password_validators_help_text_html(),)
    password2 = forms.CharField(label = 'Repeat Password', widget = forms.PasswordInput(),strip=False,help_text="Both Passwords should be same.",)
    email = forms.EmailField(label = 'Email Address', widget = forms.TextInput())
    class Meta:
        model = User
        fields = [
            'username',
           
         
        ]
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        
        emails=User.objects.all()
        for i in emails:
            if email==i.email:
    
                raise forms.ValidationError('This email already exists, check your email') 

        return email

    #Cleaning Method for password Match..........
    def clean_password2(self):
        cd = self.cleaned_data
        if self.cleaned_data.get('password') != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']

    #Cleaning Method for Email Unique..........
    def clean(self):
        if self.cleaned_data.get('email') is None:
            raise ValidationError("Enter a valid E-mail Address")
        varEmail = self.cleaned_data.get('email').lower()
        if User.objects.filter(email = varEmail).count() != 0 :
            if not User.objects.get(email = varEmail).is_active :
                User.objects.get(email = varEmail).delete()
            else:
                raise ValidationError(self.cleaned_data.get('email') + "\tAlready Exists.")
###
class contactForm(forms.Form):
    userName =  forms.CharField(label='', widget = forms.TextInput(attrs = {'placeholder' : 'Name'}))    
    email = forms.EmailField(label = '', widget = forms.TextInput(attrs = {'placeholder' : 'Email'}))
    body = forms.CharField(label='', widget=forms.Textarea(attrs = {'placeholder':'Message', 'cols' : '30', 'rows' : '10'}))




#User Extra Information ................
class profileInformForm(forms.ModelForm):
    class Meta:
        model = profileModel
        exclude=['user','approve','Teacher_or_Parent']


#User Can Edit his profile using this Form..........................
class EditProfileForm(UserChangeForm):
    password = forms.CharField(label='', widget = forms.TextInput(attrs = {'type' : 'hidden'}))
    class Meta:
        model = User
        fields = [
                  'first_name',
                  'last_name',
                  'password',
                  'email'
                  ]

ptm/mysite/views.py
from django.shortcuts import render
from django.contrib.auth.models import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .tokens import account_activation_token


from .forms import *
from .models import *


def home(request):
    # if request.user.is_authenticated and  not request.user.is_superuser:
    if request.user.is_authenticated:
        try:
            profile = profileModel.objects.get(user=request.user)
        except:
            profile = None
        if profile.approve == True:
            context = {
                'profile': profile,
                'section': 'dashboard'
            }
            if profile.Teacher_or_Parent == 'Buyer':

                return render(request, 'mysite/home2.html', context)
            if profile.Teacher_or_Parent == 'Agent':
                return render(request, 'mysite/home2.html', context)
        else:
            return render(request, 'mysite/Approve.html')
    return render(request, 'mysite/home.html')


def contact(request):
    if request.method != 'POST':
        form = contactForm()
    else:
        form = contactForm(request.POST)
        if form.is_valid():
            mail_subject = 'Contact -- By -- ' + \
                form.cleaned_data.get('userName')
            to_email = settings.EMAIL_HOST_USER
            message = form.cleaned_data.get('body')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return redirect('home')

    context = {'form': form}
    return render(request, 'mysite/contact.html', context)


def login_user(request):
    if request.method != 'POST':
        form = loginForm()
    else:
        form = loginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.warning(
                    request, 'Usename or password may have been entered incorrectly.')
                return redirect('login')

    return render(request, 'mysite/login.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('home')


def register_user(request):
    if request.method != 'POST':
        form = registerForm()
        form_2 = profileInformForm()
    else:
        form = registerForm(request.POST)
        form_2 = profileInformForm(request.POST)
        if form.is_valid() & form_2.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.set_password(form.cleaned_data['password2'])
            user.email = form.cleaned_data['email']
            user.save()
            profile = profileModel.objects.create(user=user)
            profile.contactNumber = form_2.cleaned_data['contactNumber']
            profile.Price_Range = form_2.cleaned_data['Price_Range']
            profile.occupation = form_2.cleaned_data['occupation']
            profile.has_pre_approval = form_2.cleaned_data['has_pre_approval']
            profile.property_type = form_2.cleaned_data['property_type']
            profile.beds = form_2.cleaned_data['beds']
            profile.bath = form_2.cleaned_data['bath']
            profile.lot_size = form_2.cleaned_data['lot_size']
            profile.stories = form_2.cleaned_data['stories']
            profile.location_preference = form_2.cleaned_data['location_preference']
            profile.looking_to_buy_in_how_many_months = form_2.cleaned_data['looking_to_buy_in_how_many_months']
            profile.How_long_have_you_been_house_hunting = form_2.cleaned_data['How_long_have_you_been_house_hunting']
            profile.Life_style = form_2.cleaned_data['Life_style']
            profile.any_other = form_2.cleaned_data['any_other']

            
            profile.save()
            # current_site = get_current_site(request)
            # message = render_to_string('mysite/acc_active_email.html', {
            #     'user':user, 'domain':current_site.domain,
            #     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            #     'token': account_activation_token.make_token(user),
            # })
            # mail_subject = 'Activate your account.'
            # to_email = form.cleaned_data.get('email')
            # email = EmailMessage(mail_subject, message, to=[to_email])
            # email.send()
            user = authenticate(
            request, username=form.cleaned_data['email'], password=form.cleaned_data['password'])
            login(request,user)
            return redirect('home')
    return render(request, 'mysite/register.html', {'form': form, 'form_2': form_2})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.warning(request, 'User has been activated')
        return redirect('login')
    else:
        messages.warning(request, 'Invalid Activation Link')
        return redirect('register')

# @login_required
# def edit_profile(request):
#     try:
#         profile = profileModel.objects.get(user=request.user)
#     except:
#         profile=None
#     context={
#         'profile' : profile,
#         'section' : "editProfile"
#     }
#     return render(request, 'mysite/editProfile.html', context)


@login_required()
def edit_profile(request):
    if request.method != 'POST':
        form = EditProfileForm(instance=request.user)
    else:
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            # messages.success(request, 'Profile has been updated.')
            # return redirect('home')
    try:
        profile = profileModel.objects.get(user=request.user)
    except:
        profile = profileModel.objects.create(user=request.user)
    if request.method != 'POST':
        if profile:
            form_2 = profileInformForm(instance=profile)
        else:
            form_2 = profileInformForm()
    else:
        if profile:
            form_2 = profileInformForm(request.POST, instance=profile)
        else:
            form_2 = profileInformForm(request.POST,)
        if form_2.is_valid():
            form_2.save()
            messages.success(request, 'Profile has been updated.')
            return redirect('home')

    try:
        profile = profileModel.objects.get(user=request.user)
    except:
        profile = None
    context = {
        'profile': profile,
        'section': "editProfile",
        'form': form,
        'form_2':form_2
    }
    return render(request, 'mysite/editProfile.html', context)


@login_required()
def edit_profile_user(request):
    try:
        profile = profileModel.objects.get(user=request.user)
    except:
        profile = profileModel.objects.create(user=request.user)
    if request.method != 'POST':
        if profile:
            form = profileInformForm(instance=profile)
        else:
            form = profileInformForm()
    else:
        if profile:
            form = profileInformForm(request.POST, instance=profile)
        else:
            form = profileInformForm(request.POST,)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile has been updated.')
            return redirect('home')
    try:
        profile = profileModel.objects.get(user=request.user)
    except:
        profile = None
    context = {
        'profile': profile,
        'section': "editProfile",
        'form': form
    }
    return render(request, 'mysite/editProfileUser.html', context)


@login_required()
def change_password(request):
    if request.method != 'POST':
        form = PasswordChangeForm(user=request.user)
    else:
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Password has been updated.')
            return redirect('home')
    return render(request, 'mysite/change_password.html', {'form': form, 'section': "editProfile"})

ptm/mysite/templates/mysite/Approve.html
{% extends 'base.html' %}

{% block content %}

<center><h1> Approval Pending</h1></center>
<center><p>Your account needs approval from manager, please wait for 24hours</p></center>

{% endblock %}

ptm/mysite/templates/mysite/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

ptm/mysite/templates/mysite/acc_active_email_confirm.html
{% extends "base.html" %}
{% load static %}
{% block title %}Email Verification{% endblock %}







{% block register %}
<div class="register-login-area">
                            
        <a href="{% url 'register' %}" class="btn active">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endblock  %}




{% block content %}
  
    <div class="container" style="margin-top: 150px;">
      <div class="alert alert-info">
        <strong><h1>Email Verification</h1></strong><p>Please confirm your email address to complete the registration. </p>
      </div>
      
    </div>
{% endblock content %}

ptm/mysite/templates/mysite/acc_active_sent.html
{% extends "base.html" %}
{% load static %}
{% block title %}Email Verification{% endblock %}

{% block register %}
<div class="register-login-area">
                            
        <a href="{% url 'register' %}" class="btn active">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endblock  %}



{% block content %}
    <link rel="stylesheet" type = "text/css" href="{% static 'music/css/StyleSheet3.css' %}">

    <div class="container" style="margin-top: 150px;">
      <div class="alert alert-info">
        <strong><h1>Email Verification</h1></strong><p>Please confirm your email address to complete the registration. </p>
      </div>
      
    </div>
{% endblock content %}

ptm/mysite/templates/mysite/change_password.html
{% extends "base.html" %}
{% load static %}
{% block title %}Change Password{% endblock %}
{% block content %}

<div class="mx-auto" style="width: 300px;">
            <div class="card" style="width:18rem;">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger alert-dismissible">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                <div class="card-body">

                
                <form action="{% url 'change_password' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class = "exampleInputPassword1">Old Password </label>
                        <input type="password" name="old_password" autofocus required id="id_old_password"  class="form-control"  placeholder="Enter Old Password">
                    <div>
                        <br>
                    <div class="form-group">
                        <label class = "exampleInputPassword2">New Password</label>
                        <input type="password" name="new_password1" required id="id_new_password1"  class="form-control"  placeholder="Enter New Password">
                        <small id="passwordHelpInline" class="text-muted">
                                <ul>
                                    <li>Your password can&#39;t be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can&#39;t be a commonly used password.</li>
                                    <li>Your password can&#39;t be entirely numeric.</li>
                                </ul>
                        </small>
                    <div>
                        <br>
                            <div class="form-group">
                                    <label class = "exampleInputPassword3">Confirm New Password</label>
                                    <input type="password" name="new_password2" required id="id_new_password2"  class="form-control"  placeholder="Enter New Confirm Password">
                                <div>
                        <br>
                    <button type="submit" class="btn btn-primary" value="Change Password">Change Password</button>
                    
                </form>
            </div>
            </div>

        </div>
{% endblock content %}

ptm/mysite/templates/mysite/contact.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Contact {% endblock %}




{% block register %}
{% if request.user.is_authenticated %}
    <div class="register-login-area">
                                
            <a href="{% url 'editProfile'   %}" class="btn text-white">{{ request.user.username}}</a>
            <a href="{% url 'logout' %}" class="btn text-white">Logout</a>
        
        </div>

{% else %}

<div class="register-login-area">
                                
        <a href="{% url 'register' %}" class="btn text-white">SignUp</a>
        <a href="{% url 'login' %}" class="btn text-white">Login</a>
    
    </div>
{% endif %}

    {% endblock  %}






{% block content %}

<br>
<br>
<br>
<br>

    <!-- ##### Contact Area Start ##### -->
    <section class="contact-area">
        <div class="container">
            <div class="row">
                <!-- Contact Info -->
                <div class="col-12 col-lg-6">
                    <div class="contact--info mt-50 mb-100">
                        <h4>Contact Info</h4>
                        <ul class="contact-list">
                            <li>
                                <h6><i class="fa fa-clock-o" aria-hidden="true"></i> Business Hours</h6>
                                <h6>8:00 AM - 4:00 PM</h6>
                            </li>
                            <li>
                                <h6><i class="fa fa-phone" aria-hidden="true"></i> Number</h6>
                                <h6>+64331-4307703</h6>
                            </li>
                            <li>
                                <h6><i class="fa fa-envelope" aria-hidden="true"></i> Email</h6>
                                <h6>abckindergar@gmail.com</h6>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Contact Form -->
                <div class="col-12 col-lg-6">
                    <div class="contact-form">
                        <h4>Get In Touch</h4>
                        
                        <form action="{% url 'contact' %}" method="post">
                            {% csrf_token %}

                            
                            <div class="row">
                                <div class="col-12 col-lg-6">
                                    <div class="form-group">
                                        <input type="text" name="userName" placeholder="Name" required id="id_userName" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6">
                                    <div class="form-group">
                                        <input type="text" name="email" placeholder="Email" required id="id_email" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <textarea name="body" class="form-control" cols="30" rows="10" placeholder="Message" required id="id_body"></textarea>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn clever-btn w-100">Send</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->


{% endblock %}

ptm/mysite/templates/mysite/editProfileUser.html
{% extends 'base.html' %}

{% block title %}Real State{% endblock %}

{% block content %}

<div class="mx-auto mb-5" style="width: 350px;">
<div class="card" style="width: 22rem;">
    
    <div class="card-body">
      <form action="{% url 'editProfileUSer' %}" method="POST">
        {% csrf_token %}
      <h5 class="card-title font-weight-bold">{{ request.user.username }}</h5>
      <table class="table">
          
          <tbody>
            <tr>
              
              <td>username</td>
              <td><input class="form-control border-0 bg-transparent" name="username" type="text" placeholder="{{ request.user.username }}" value="{{ request.user.username }}" readonly></td>
              
            </tr>

              {% if profile %}
              <tr>
             
                  
                  
                </tr>
                <tr>
              
                    <td>Phone</td>
                    <td>
                            <input class="form-control border-0 bg-transparent" name="contactNumber" type="text" placeholder="{{ profile.contactNumber }}" value="{{ profile.contactNumber }}" >

                    </td>
                    
                    
                  </tr>
                {% endif %}

                <tr>
                    <td colspan="2" class="border-0">
                      <input type="submit" value="Edit Profile Information" class="btn btn-primary">
                    </td>
                  </tr>
                  
          </tbody>
        </table>
      </form>
    </div>
  </div>
</div>
{% endblock %}

ptm/mysite/templates/mysite/register.html
{% extends "base.html" %}
{% block title %}Registration{% endblock %}



{% block content %}

<style>
        input::-webkit-inner-spin-button,
        input::-webkit-outer-spin-button {
                -webkit-appearance: none;
        }

        input[type="number"] {
                -moz-appearance: textfield;
        }
</style>

<div class="mx-auto mt-5" style="width: 300px;">

<div class="card" style="width: 22rem;">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger alert-dismissible">
                <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}

        {% if form_2.errors %}
        {% for field in form_2 %}
        {% for error in field.errors %}
        <div class="alert alert-danger alert-dismissible">
                <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% endif %}

        {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger alert-dismissible">
                                <strong>{{ message|escape }}</strong>
                        </div>
                {% endfor %}          
        {% endif %}

        <div class="card-body">
                <form action="{% url 'register' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                                <label for="id_email">Email Address</label>
                                <input type="email" name="email" required id="id_email" class="form-control"
                                        placeholder="Enter Email">

                        </div>
                        <!-- <div class="form-group">
                                <label for="id_username">Username</label>
                                <input type="text" name="username" maxlength="150" required id="id_username"
                                        class="form-control" placeholder="Enter User">
                                <small id="usernameHelpInline" class="text-muted">
                                        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                                </small>
                        </div> -->

                        <div class="form-group">
                                <label for="id_username">Name</label>
                                <input type="text" name="username" maxlength="30" id="id_username"
                                        class="form-control" placeholder="Enter Name">
                        </div>

                     

                        <div class="form-group">
                                <label for="id_password">Password</label>
                                <input type="password" name="password" required id="id_password" class="form-control"
                                        placeholder="Enter Password">
                                <small id="passwordHelpInline" class="text-muted">
                                        <ul>
                                                <li>Your password can&#39;t be too similar to your other personal
                                                        information.</li>
                                                <li>Your password must contain at least 8 characters.</li>
                                                <li>Your password can&#39;t be a commonly used password.</li>
                                                <li>Your password can&#39;t be entirely numeric.</li>
                                        </ul>
                                </small>
                        </div>

                        <div class="form-group">
                                <label for="id_password2">Confirm Password</label>
                                <input type="password" name="password2" required id="id_password2" class="form-control"
                                        placeholder="Enter Confirm Password">
                                <small id="passwordHelpInline" class="text-muted">
                                        Both Passwords should be same.
                                </small>
                        </div>

                
                        <!-- <div class="form-group">
                                        <label for="exampleFormControlSelect2">Buyer or Agent</label>
                                        <select  class="form-control" id="exampleFormControlSelect2" name="Teacher_or_Parent">
                                          <option value="Buyer" selected>Buyer</option>
                                          <option value="Agent">Agent</option>
                                        </select>
                                      </div> -->

                        <div class="form-group">
                                <label for="id_contactNumber">Phone</label>
                                <input type="number" name="contactNumber" id="id_contactNumber" class="form-control"
                                        placeholder="Enter Phone Number">
                        </div>

                        <button type="submit" class="btn btn-primary" value="Sign-Up">Sign Up</button>

                </form>

        </div>
</div>

</div>

{% endblock %}